### PR TITLE
Revendor github.com/openshift/generic-admission-server

### PR DESCRIPTION
**Pull request by tamalsaha**
ref: https://github.com/openshift/generic-admission-server/pull/6

### CODE REVIEW

**Comment by deads2k** [comment]
close and open to kick travis

**Comment by deads2k** [comment]
Looks like a legit build failure:

```
# github.com/openshift/kubernetes-namespace-reservation/cmd/namespacereservationserver
cmd/namespacereservationserver/main.go:20:2: undefined: cmd.RunAdmission
```

**Comment by tamalsaha** [comment]
Test fixed . PTAL!

**Comment by deads2k** [comment]
lgtm

**Pull request merged**
